services:
  toppview-lite:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: toppview-lite
    container_name: toppview-lite
    restart: always
    ports:
      - 8501:8501
    volumes:
      - workspaces-toppview-lite:/app/workspaces
volumes:
  workspaces-toppview-lite:
